var automationframework = connect('localhost:27017/automationframework');
//test comment
var BrowserVarID = ObjectId();
var ClickID = ObjectId();
var OpenBrowserID = ObjectId();
var SendKeysID = ObjectId();
var VerifyTextID = ObjectId();


//actions
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361857038191-12505-27095"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361857045292-1778-6378"}],"name":"Click on Element","description":"Click on element","type":"script","status":"Automated","_id":ClickID,"collection":[],"script":"actions.selenium.Click.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"URL","possiblevalues":[],"parametertype":"String","id":"1361857291996-19836-917"},{"name":"Browser Type","possiblevalues":["Internet Explorer","Firefox","Chrome"],"parametertype":"String","id":"1361857319350-22783-32022"}],"name":"Open Browser","description":"","type":"script","status":"Automated","_id":OpenBrowserID,"collection":[],"script":"actions.selenium.Browser.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361859197536-31667-17007"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361859201529-30055-7133"},{"name":"Key","possiblevalues":[],"parametertype":"String","id":"1361859371895-8512-9755"},{"name":"Text","possiblevalues":[],"parametertype":"String","id":"1361859371895-8512-9793"}],"name":"Send Keys to Element","description":"Look up http://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/Keys.html for key names","type":"script","status":"Automated","_id":SendKeysID,"collection":[],"script":"actions.selenium.SendKeys.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Text","possiblevalues":[],"parametertype":"String","id":"1361900791173-11855-8017"}],"name":"Verify Text in Element","description":"","type":"script","status":"Automated","_id":VerifyTextID,"collection":[],"script":"actions.selenium.VerifyText.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[],"name":"Close All Browsers","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.CloseBrowser.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[],"name":"Close Current Window","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.CloseWindow.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"Window Name","possiblevalues":["Default Window"],"parametertype":"String","id":"1361900718349-8440-28310"}],"name":"Switch to Browser Window","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.SwitchWindow.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"}],"name":"Submit Form","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.Submit.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"}],"name":"Right Click on Element","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.RightClick.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"}],"name":"Mouse Over Element","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.MouseOver.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Number of Matches","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28333"}],"name":"Verify Element Exists","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.Exists.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"URL","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"}],"name":"Navigate to URL","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.NavigateToURL.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Is Checked","possiblevalues":[],"parametertype":"Boolean","id":"1361900718349-8440-28333"}],"name":"Verify Checkbox","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.VerifyCheckBox.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"Cookie Name","possiblevalues":["ALL"],"parametertype":"String","id":"1361900718349-8440-28310"}],"name":"Delete Cookie","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.DeleteCookie.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"}],"name":"Double Click on Element","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.DoubleClick.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"Name","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"Index","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28312"}],"name":"Switch To Frame","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.SwitchToFrame.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[],"name":"Switch To Default Content","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.SwitchToDefaultContent.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Is Enabled","possiblevalues":[],"parametertype":"Boolean","id":"1361900718349-8440-28333"},{"name":"Is Visible","possiblevalues":[],"parametertype":"Boolean","id":"1361900718349-9440-28344"},{"name":"Is Focused","possiblevalues":[],"parametertype":"Boolean","id":"1361900718349-9440-28888"}],"name":"Verify Element State","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.VerifyElementState.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"Code","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"}],"name":"Execute Javascript","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.ExecuteJavascript.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"}],"name":"Set Focus on Element","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.SetFocus.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"Name","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"}],"name":"Get Cookie Value","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.GetCookieValue.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Attribute Name","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28311"},{"name":"Value","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28314"}],"name":"Verify Element Attribute","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.VerifyAttribute.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Item Label","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28311"},{"name":"Item Value","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28314"}],"name":"Verify Selected List Item","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.VerifySelectedItem.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"Title","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"}],"name":"Verify Page Title","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.VerifyPageTitle.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"}],"name":"Get Element Text","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.GetText.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[],"name":"Refresh","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.Refresh.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[],"name":"Go Forward","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.GoForward.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[],"name":"Go Back","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.GoBack.run","project":projectName});
automationframework.actions.save({"tag":["general"],"params":[{"name":"Seconds","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"}],"name":"Wait","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.general.Wait.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"From ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"From ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"To ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28322"},{"name":"To ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16328"}],"name":"Drag And Drop to Element","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.DragAndDrop.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"Value","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"Regular Expression","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28319"}],"name":"Verify Current URL Value","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.VerifyURL.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Check","possiblevalues":[],"parametertype":"Boolean","id":"1361900718349-8440-28319"}],"name":"Set Checkbox","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.SetCheckBox.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"Seconds","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"}],"name":"Set Timeout","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.SetTimeout.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Timeout In Seconds","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28319"}],"name":"Wait for Element","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.WaitForElement.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Text","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28319"}],"name":"Set Text to Element","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.SetText.run","project":projectName});
automationframework.actions.save({"tag":["selenium"],"params":[{"name":"ID","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28310"},{"name":"ID Type","possiblevalues":["ID","XPath","Class Name","Tag Name","Css Selector","Link Text","Partial Link Text","Name"],"parametertype":"String","id":"1361900724396-8476-16304"},{"name":"Visible Text","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28322"},{"name":"Value","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28335"},{"name":"Index","possiblevalues":[],"parametertype":"String","id":"1361900718349-8440-28337"}],"name":"Select Item In Element","description":"","type":"script","status":"Automated","_id":ObjectId(),"collection":[],"script":"actions.selenium.SelectItem.run","project":projectName});

// Insert veriables
automationframework.variables.save({"tag":[""],"name":"Browser","value":"<NULL>","taskVar":true,"possibleValues":["Internet Explorer","Firefox","Chrome"],"project":projectName,"_id":BrowserVarID});
// Add tags
automationframework.actionTags.save({"value":"selenium","project":projectName,"_id":ObjectId()});
automationframework.actionTags.save({"value":"general","project":projectName,"_id":ObjectId()});
